In [3]:
import pandas as pd

regional_totals = pd.read_excel('../Data/SIPRI-Milex-data-1949-2025.xlsx', sheet_name='Regional totals', header=13)

regional_totals.head()

,Region,1988,1989,1990,1991,1992,1993,1994,1995,1996,...,2018,2019,2020,2021,2022,2023,2024,2024 (current prices),Unnamed: 39,Omitted countries
0,World,1749.513663,1728.656861,1660.735248,...,1388.099675,1325.224149,1291.566313,1220.729826,1186.060557,...,2038.928716,2124.480202,2200.364596,2222.600667,2294.524212,2447.444388,2676.513886,2718.183719,NaN,NaN
1,Africa,20.855433,21.216506,21.077700,18.319674,16.843798,19.301099,26.126246,15.909807,15.054588,...,40.632373,41.137544,42.346617,44.437612,42.452403,50.180443,51.706139,52.052915,NaN,"Djibouti, Eritrea, Somalia"
2,North Africa,3.446906,3.589976,3.575339,3.697637,4.206792,4.429040,4.800439,4.576832,4.850587,...,18.267512,19.189050,19.851494,18.964189,18.258387,26.230783,28.529605,30.201147,NaN,NaN
3,sub-Saharan Africa,17.408527,17.626530,17.502362,14.622037,12.637005,14.872059,21.325807,11.332975,10.204002,...,22.364860,21.948494,22.495123,25.473423,24.194017,23.949659,23.176534,21.851768,NaN,NaN
4,Americas,862.529259,853.487763,815.081594,721.208578,755.456463,722.241450,690.604064,652.938226,617.257371,...,919.632287,966.378940,1010.601645,999.084858,987.104508,1009.576673,1068.399237,1100.039531,NaN,Cuba

In [6]:
country_totals_usd = pd.read_excel('../Data/SIPRI-Milex-data-1949-2025.xlsx', sheet_name='Current US$', header=5)

country_totals_usd.head()

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,...,...,...,...,...,...,...,...,...,10407.345244,10217.0817,10073.364021,9583.724288,10303.600575,9708.27744,9112.461105,9145.810174,18263.967968,21811.242555
4,Libya,‡§¶16,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,1214.864558,1573.682777,...

In [7]:
share_of_gdp = pd.read_excel('../Data/SIPRI-Milex-data-1949-2025.xlsx', sheet_name='Share of GDP', header=5)

share_of_gdp.head()

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,...,...,...,...,...,...,...,...,...,0.055507,0.056527,0.053071,0.049299,0.05327,0.058861,0.0489,0.040575,0.073904,0.079715
4,Libya,‡§¶16,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,0.043467,0.052871,...

In [11]:
per_capita = pd.read_excel('../Data/SIPRI-Milex-data-1949-2025.xlsx', sheet_name='Per capita', header=6)

per_capita.head()

,Country,Notes,1988,1989,1990,1991,1992,1993,1994,1995,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,§4,43.257136,34.95503,36.07121,22.002806,40.060155,47.356145,48.383894,43.8054,...,262.745399,252.716656,244.072592,227.609469,240.154778,222.23366,205.240233,202.686217,398.506861,469.089244
3,Libya,‡§¶16,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,169.224761,216.492334,...
4,Morocco,§17,39.403288,41.756812,44.282009,46.696174,49.133201,49.242222,52.900264,54.894201,...,94.985712,95.587884,98.222568,103.692835,103.28977,132.740463,146.254597,134.513601,138.176324,145.587831