In [ ]:
import pandas as pd

cur = pd.read_excel('../Data/Class_2025_10_07.xlsx')
cur.head()

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN

In [6]:
# historic data

hist = pd.read_excel('../Data/World_bank_hist.xlsx', header =1)
hist.head()

,Country,FY89,FY90,FY91,FY92,FY93,FY94,FY95,FY96,FY97,...,FY17,FY18,FY19,FY20,FY21,FY22,FY23,FY24,FY25,FY26
0,Afghanistan,L,L,L,L,L,L,L,L,L,...,L,L,L,L,L,L,L,L,L,L
1,Albania,..,..,..,LM,LM,LM,L,L,L,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
2,Algeria,UM,UM,LM,LM,LM,LM,LM,LM,LM,...,UM,UM,UM,UM,LM,LM,LM,LM,UM,UM
3,American Samoa,H,H,H,UM,UM,UM,UM,UM,UM,...,UM,UM,UM,UM,UM,UM,UM,H,H,H
4,Andorra,..,..,..,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H